name = "microgpt"
version = "0.1.0"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
simplifile = ">= 2.0.0 and < 3.0.0"
gleam_community_maths = ">= 2.0.1 and < 3.0.0"
